#!/bin/bash
echo '########## yum update all ###############'
sudo yum update -y

echo '########## install oci-cli and kubectl ##############'
sudo yum install python-oci-cli kubectl git -y

sudo systemctl enable ocid.service
sudo systemctl start ocid.service
sudo systemctl status ocid.service

sudo git clone https://github.com/diogoshibata/terraform-oke.git

sudo mkdir -p ~/.oci
sudo cp terraform-oke/userdata/oci_api_key.pem ~/.oci/oci_api_key.pem
sudo cp terraform-oke/userdata/config ~/.oci/config

sudo oci setup repair-file-permissions --file ~/.oci/oci_api_key.pem
sudo oci setup repair-file-permissions --file ~/.oci/config